package br.com.worklink.application.authorization.usecase;

public enum SensitiveAction {

    REGISTER_SERVICE_CATEGORY,
    REGISTER_SERVICE_CITY,
    COMPLETE_PROFESSIONAL_PROFILE,
    ACCESS_ADMINISTRATIVE_DATA,
    ACCESS_PRIVATE_CUSTOMER_DATA,
    ACCESS_INTERNAL_REVIEW_AUTHORSHIP,
    ACCESS_THIRD_PARTY_REPORT,
    BLOCK_PROFESSIONAL,
    UNBLOCK_PROFESSIONAL
}
