package br.com.worklink.application.privacy.usecase;

public enum PersonalDataField {
    PROFESSIONAL_NAME,
    PROFESSIONAL_WHATSAPP_NUMBER,
    PROFESSIONAL_CITY,
    PROFESSIONAL_CATEGORY,
    PROFESSIONAL_SHORT_DESCRIPTION,
    PROFESSIONAL_PROFILE_PHOTO_REFERENCE,
    PROFESSIONAL_DOCUMENT_NUMBER_HASH,
    PROFESSIONAL_PORTFOLIO_DESCRIPTION,
    PROFESSIONAL_SERVICE_DESCRIPTION,
    CUSTOMER_PHONE_NUMBER,
    AUTHENTICATION_ONE_TIME_PASSWORD_HASH,
    AUTHENTICATION_REFRESH_TOKEN_HASH,
    APPROXIMATE_LOCATION,
    REPORT_EVIDENCE_REFERENCE,
    REVIEW_INTERNAL_AUTHOR_IDENTIFIER,
    BANK_ACCOUNT,
    CREDIT_CARD,
    PHOTO_DOCUMENT,
    CONTINUOUS_REAL_TIME_LOCATION,
    FINANCIAL_INFORMATION
}
