package br.com.worklink.application.audit.usecase;

public enum SensitiveAuditAction {

    ADMINISTRATIVE_LOGIN,
    REGISTER_SERVICE_CATEGORY,
    REGISTER_SERVICE_CITY,
    COMPLETE_PROFESSIONAL_PROFILE,
    ADD_PROFESSIONAL_PORTFOLIO_ITEM,
    REQUEST_PROFESSIONAL_PHONE_VERIFICATION,
    CONFIRM_PROFESSIONAL_PHONE_VERIFICATION,
    UPDATE_PROFESSIONAL_AVAILABILITY,
    REGISTER_CONTACT_INTENTION,
    REGISTER_POST_CONTACT_FEEDBACK,
    REGISTER_ANONYMOUS_REVIEW,
    REQUEST_REVIEW_ANALYSIS,
    ACCESS_INTERNAL_REVIEW_AUTHORSHIP,
    REGISTER_PROFESSIONAL_REPORT,
    ACCESS_CONFIDENTIAL_EVIDENCE,
    CONTEST_PROFESSIONAL_REPORT,
    ACCESS_ADMINISTRATIVE_DATA,
    BLOCK_PROFESSIONAL,
    UNBLOCK_PROFESSIONAL
}
